<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'phpDocumentor' => array($vendorDir . '/phpdocumentor/reflection-docblock/src'),
    'Way\\Generators' => array($vendorDir . '/way/generators/src'),
    'Psy\\' => array($vendorDir . '/psy/psysh/src'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Prophecy\\' => array($vendorDir . '/phpspec/prophecy/src'),
    'PhpSpec' => array($vendorDir . '/phpspec/phpspec/src'),
    'PHPPowerPoint' => array($vendorDir . '/phpoffice/phppowerpoint/src'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Lavender\\Cloud' => array($vendorDir . '/chekun/laravel4sae/src'),
    'Jenssegers\\Mongodb' => array($vendorDir . '/jenssegers/mongodb/src'),
    'Jenssegers\\Eloquent' => array($vendorDir . '/jenssegers/mongodb/src'),
    'JakubOnderka\\PhpConsoleHighlighter' => array($vendorDir . '/jakub-onderka/php-console-highlighter/src'),
    'JakubOnderka\\PhpConsoleColor' => array($vendorDir . '/jakub-onderka/php-console-color/src'),
    'Guzzle\\Tests' => array($vendorDir . '/guzzle/guzzle/tests'),
    'Guzzle' => array($vendorDir . '/guzzle/guzzle/src'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
    'Dotenv' => array($vendorDir . '/vlucas/phpdotenv/src'),
    'Doctrine\\Common\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
    'Cron' => array($vendorDir . '/mtdowling/cron-expression/src'),
    'Cartalyst\\Sentry' => array($vendorDir . '/cartalyst/sentry/src'),
    'Carbon' => array($vendorDir . '/nesbot/carbon/src'),
    'BrainSocket' => array($vendorDir . '/brainboxlabs/brain-socket/src'),
);
